### ISSUE TITLE
staging.py lijkt vereist voor installatie

### ISSUE THREAD

**Issue by frankmijn** [Haarlem/zaakregistratiecomponent#13]
Op deze pagina [https://github.com/frankmijn/zaakregistratiecomponent/tree/master/deployment/centos](https://github.com/frankmijn/zaakregistratiecomponent/tree/master/deployment/centos) bij stap 6 staat dat je een willekeurige naam kan kiezen. Ik had production.py gekozen en aangepast maar hij vraagt dan toch ergens om staging.py. Met staging.py werkt hij wel goed. Lijkt alsof er nog iets hard geconfigureerd staat maar kan ook iets anders zijn.

**Comment by BoerBas** [comment]
@joeribekker kan jij naar deze issue en PR kijken? 

Frankmijn, bedankt voor je input, we gaan er mee aan de slag en komen er op terug.

**Comment by frankmijn** [comment]
@joeribekker dat zal hem zijn, ik had niet in dat bestand gekeken. Vond hem niet blokkerend (want werkt gewoon met staging) dus omheen gewerkt. Voor de volgende keer neem ik deze mee.

**Comment by joeribekker** [comment]
Het liefst moet dit natuurlijk automagisch goed gezet worden tijdens de setup, maar mijn `sed` skills zijn matig. Vandaar dat ik het "opgelost" heb in de documentatie.

**Comment by BoerBas** [comment]
@joeribekker issue sluiten? En wat te doen met de PR? Kan jij die bekijken?

**Comment by joeribekker** [comment]
Volgens mij is dit opgelost.
